package boundary;

import com.toedter.calendar.JDateChooser;
import control.OrderControl;
import control.PersonControl;
import control.WineControl;
import entity.Customer;
import entity.Employee;
import entity.UrgentOrder;
import enums.CurrentStatus;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FrmAddUrgentOrder extends JFrame {

    // Header fields
    private JTextField tfOrderID, tfEmployeeID, tfCustomerID, tfPriority;
    private JDateChooser dcOrderDate, dcShipmentDate, dcExpectedDelivery;
    private JComboBox<CurrentStatus> cbStatus;

    // Wine selection table components
    private JTable wineTable;
    private DefaultTableModel wineTableModel;
    private JScrollPane wineScrollPane;

    // Confirm button
    private JButton btnConfirm;

    // List to hold wine selections
    public static class WineSelection {
        private int wineId;
        private int quantity;
        private double totalPrice;

        public WineSelection(int wineId, int quantity, double totalPrice) {
            this.wineId = wineId;
            this.quantity = quantity;
            this.totalPrice = totalPrice;
        }
        public int getWineId() { return wineId; }
        public int getQuantity() { return quantity; }
        public double getTotalPrice() { return totalPrice; }
    }
    private List<WineSelection> wineSelections = new ArrayList<>();

    public FrmAddUrgentOrder() {
    	setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(650, 550);
        setLocationRelativeTo(null);
        
        setBackground(new Color(105,20,56));
        setLayout(new BorderLayout(10,10));

        // Create header panel for order details
        JPanel headerPanel = new JPanel(new GridBagLayout());
        headerPanel.setBackground(new Color(69,16,32));
        headerPanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(new Color(234,171,55)), 
                "Urgent Order Header",
                TitledBorder.DEFAULT_JUSTIFICATION, 
                TitledBorder.DEFAULT_POSITION, 
                new Font("Arial", Font.BOLD, 14), 
                new Color(234,171,55)
        ));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5,5,5,5);
        gbc.anchor = GridBagConstraints.WEST;
        
        // Row 0: Order ID & Employee ID
        gbc.gridx = 0; gbc.gridy = 0;
        JLabel lblOrderID = new JLabel("Order ID:");
        lblOrderID.setForeground(Color.YELLOW);
        headerPanel.add(lblOrderID, gbc);
        tfOrderID = new JTextField(10);
        tfOrderID.setEditable(false);
        tfOrderID.setForeground(Color.YELLOW);
        tfOrderID.setBackground(new Color(217,166,165));
        tfOrderID.setText("AutoGenerated");
        gbc.gridx = 1;
        headerPanel.add(tfOrderID, gbc);
        
        gbc.gridx = 2;
        JLabel lblEmployeeID = new JLabel("Employee ID:");
        lblEmployeeID.setForeground(Color.YELLOW);
        headerPanel.add(lblEmployeeID, gbc);
        tfEmployeeID = new JTextField(10);
        tfEmployeeID.setForeground(Color.YELLOW);
        tfEmployeeID.setBackground(new Color(217,166,165));
        gbc.gridx = 3;
        headerPanel.add(tfEmployeeID, gbc);
        
        // Row 1: Customer ID & Priority
        gbc.gridx = 0; gbc.gridy = 1;
        JLabel lblCustomerID = new JLabel("Customer ID:");
        lblCustomerID.setForeground(Color.YELLOW);
        headerPanel.add(lblCustomerID, gbc);
        tfCustomerID = new JTextField(10);
        tfCustomerID.setForeground(Color.YELLOW);
        tfCustomerID.setBackground(new Color(217,166,165));
        gbc.gridx = 1;
        headerPanel.add(tfCustomerID, gbc);
        
        gbc.gridx = 2;
        JLabel lblPriority = new JLabel("Priority:");
        lblPriority.setForeground(Color.YELLOW);
        headerPanel.add(lblPriority, gbc);
        tfPriority = new JTextField(5);
        tfPriority.setForeground(Color.YELLOW);
        tfPriority.setBackground(new Color(217,166,165));
        gbc.gridx = 3;
        headerPanel.add(tfPriority, gbc);
        
        // Row 2: Dates
        gbc.gridx = 0; gbc.gridy = 2;
        JLabel lblOrderDate = new JLabel("Order Date:");
        lblOrderDate.setForeground(Color.YELLOW);
        headerPanel.add(lblOrderDate, gbc);
        dcOrderDate = new JDateChooser();
        dcOrderDate.setDate(new Date());
        gbc.gridx = 1;
        headerPanel.add(dcOrderDate, gbc);
        
        gbc.gridx = 2;
        JLabel lblShipmentDate = new JLabel("Shipment Date:");
        lblShipmentDate.setForeground(Color.YELLOW);
        headerPanel.add(lblShipmentDate, gbc);
        dcShipmentDate = new JDateChooser();
        dcShipmentDate.setDate(new Date());
        gbc.gridx = 3;
        headerPanel.add(dcShipmentDate, gbc);
        
        // Row 3: Expected Delivery & Status
        gbc.gridx = 0; gbc.gridy = 3;
        JLabel lblExpectedDelivery = new JLabel("Expected Delivery:");
        lblExpectedDelivery.setForeground(Color.YELLOW);
        headerPanel.add(lblExpectedDelivery, gbc);
        dcExpectedDelivery = new JDateChooser();
        dcExpectedDelivery.setDate(new Date());
        gbc.gridx = 1;
        headerPanel.add(dcExpectedDelivery, gbc);
        
        gbc.gridx = 2;
        JLabel lblStatus = new JLabel("Status:");
        lblStatus.setForeground(Color.YELLOW);
        headerPanel.add(lblStatus, gbc);
        cbStatus = new JComboBox<>();
        for (CurrentStatus s : CurrentStatus.values()) {
            cbStatus.addItem(s);
        }
        cbStatus.setSelectedItem(CurrentStatus.IN_PROCESS);
        gbc.gridx = 3;
        headerPanel.add(cbStatus, gbc);
        
        add(headerPanel, BorderLayout.NORTH);

        // Create wine selection table panel
        JPanel winePanel = new JPanel(new BorderLayout());
        winePanel.setBackground(new Color(69,16,32));
        winePanel.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(new Color(234,171,55)),
                "Wine Selection",
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION,
                new Font("Arial", Font.BOLD, 14),
                new Color(234,171,55)
        ));
        
        // Wine table columns: Select, Wine ID, Wine Name, Price per Bottle, Quantity, Total Price
        String[] wineCols = {"Select", "Wine ID", "Wine Name", "Price per Bottle", "Quantity", "Total Price"};
        wineTableModel = new DefaultTableModel(wineCols, 0) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if(columnIndex == 0) return Boolean.class;
                if(columnIndex == 1) return Integer.class;
                if(columnIndex == 3) return Double.class;
                if(columnIndex == 4) return Integer.class;
                if(columnIndex == 5) return Double.class;
                return String.class;
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 0 || column == 4; // Only allow checkbox and quantity editing.
            }
        };
        // Populate wine table using available wines (assumed: WineControl.getAvailableWines() returns Object[][] {wineID, wineName, price})
        Object[][] wines = WineControl.getAvailableWines();
        for(Object[] wine : wines) {
            int wineId = (Integer) wine[0];
            String wineName = wine[1].toString();
            double price = (Double) wine[2];
            int defaultQty = 1;
            double totalPrice = defaultQty * price;
            wineTableModel.addRow(new Object[]{false, wineId, wineName, price, defaultQty, totalPrice});
        }
        wineTable = new JTable(wineTableModel);
        wineTable.setBackground(new Color(105,20,56));
        wineTable.setForeground(new Color(234,171,55));
        wineTable.getTableHeader().setBackground(new Color(234,171,55));
        wineTable.getTableHeader().setForeground(new Color(105,20,56));
        // Listener: update total price when quantity changes.
        wineTable.getModel().addTableModelListener(e -> {
            int row = e.getFirstRow();
            int col = e.getColumn();
            if(col == 4) {
                try {
                    int qty = Integer.parseInt(wineTableModel.getValueAt(row, 4).toString());
                    double price = (Double) wineTableModel.getValueAt(row, 3);
                    double total = qty * price;
                    wineTableModel.setValueAt(total, row, 5);
                } catch(NumberFormatException ex) {
                    // Handle error if needed.
                }
            }
        });
        wineScrollPane = new JScrollPane(wineTable);
        wineScrollPane.getViewport().setBackground(new Color(105,20,56));
        winePanel.add(wineScrollPane, BorderLayout.CENTER);
        add(winePanel, BorderLayout.CENTER);

        // Confirm button panel
        JPanel btnPanel = new JPanel();
        btnPanel.setBackground(new Color(69,16,32));
        btnConfirm = new JButton("Confirm Order");
        btnConfirm.setBackground(new Color(194,65,78));
        btnConfirm.addActionListener(this::confirmOrder);
        btnPanel.add(btnConfirm);
        add(btnPanel, BorderLayout.SOUTH);
    }

    // Gather wine selections from the wine table.
    private void saveWineSelections() {
        wineSelections.clear();
        for (int i = 0; i < wineTableModel.getRowCount(); i++) {
            Boolean isSelected = (Boolean) wineTableModel.getValueAt(i, 0);
            if (isSelected != null && isSelected) {
                int wineId = (Integer) wineTableModel.getValueAt(i, 1);
                int quantity = (Integer) wineTableModel.getValueAt(i, 4);
                double totalPrice = (Double) wineTableModel.getValueAt(i, 5);
                wineSelections.add(new WineSelection(wineId, quantity, totalPrice));
            }
        }
    }

    // Confirm order: read header fields and wine selections, then create and insert an urgent order.
    private void confirmOrder(ActionEvent e) {
        // Read header fields.
        String empIdStr = tfEmployeeID.getText().trim();
        String custIdStr = tfCustomerID.getText().trim();
        String priorityStr = tfPriority.getText().trim();
        
        if (empIdStr.isEmpty() || custIdStr.isEmpty() || priorityStr.isEmpty() ||
            dcOrderDate.getDate() == null || dcShipmentDate.getDate() == null || dcExpectedDelivery.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all header details.");
            return;
        }
        
        int empId, custId, priority;
        try {
            empId = Integer.parseInt(empIdStr);
            custId = Integer.parseInt(custIdStr);
            priority = Integer.parseInt(priorityStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Employee ID, Customer ID, and Priority must be numbers.");
            return;
        }
        
        Employee employee = PersonControl.getInstance().getEmployeeById(empId);
        Customer customer = PersonControl.getInstance().getCustomerById(custId);
        if (employee == null || customer == null) {
            JOptionPane.showMessageDialog(this, "Invalid Employee or Customer ID.");
            return;
        }
        
        // Save wine selections.
        saveWineSelections();
        if (wineSelections.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No wines selected.");
            return;
        }
        
        // Create the urgent order object.
        UrgentOrder urgentOrder = new UrgentOrder(
                custId,
                dcExpectedDelivery.getDate(),
                null,
                dcExpectedDelivery.getDate(),
                employee,
                dcExpectedDelivery.getDate(),
                null,
                custId);
        urgentOrder.setOrder_Date(dcOrderDate.getDate());
        urgentOrder.setShipment_Date(dcShipmentDate.getDate());
        urgentOrder.setEmployee_ID(employee);
        urgentOrder.setExpectedDeliveryDate(dcExpectedDelivery.getDate());
        urgentOrder.setPriorityLevel(priority);
        urgentOrder.setCustomer(customer);
        urgentOrder.setCurrentStatus((CurrentStatus) cbStatus.getSelectedItem());
        
        // Insert the urgent order header.
        int orderInserted = OrderControl.getInstance().addUrgentOrder(urgentOrder);
        if (orderInserted == -1) {
            JOptionPane.showMessageDialog(this, "Failed to insert urgent order.");
            return;
        }
        int orderIdInserted = urgentOrder.getOrder_ID();
        
        // Insert wine selections as order details.
        boolean allInserted = true;
        for (WineSelection ws : wineSelections) {
            boolean detailInserted = OrderControl.getInstance().addUrgentOrderDetail(orderIdInserted, ws.getWineId(), ws.getQuantity(), ws.getTotalPrice());
            if (!detailInserted) {
                allInserted = false;
                break;
            }
        }
        if (allInserted) {
            JOptionPane.showMessageDialog(this, "Urgent order confirmed and saved successfully.");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error saving one or more urgent order details.");
        }
    }

    
}
